Repository JoinColony/purser, pull requests merged in 2018-09, with the labels that each got.

#130 Update link to CONTRIBUTE.md
  .github/CONTRIBUTE.md
  README.md
  docs/_Docs_Contribute.md
  modules/node_modules/@colony/purser-core/README.md
  modules/node_modules/@colony/purser-ledger/README.md
  modules/node_modules/@colony/purser-metamask/README.md
  modules/node_modules/@colony/purser-software/README.md
  modules/node_modules/@colony/purser-trezor/README.md
Labels: bug

#132 fix minor typo in README.md
  README.md
  docs/_Docs_Overview.md
  modules/node_modules/@colony/purser-software/README.md
  modules/node_modules/@colony/purser-software/package.json
Labels: bug

#137 Manually update packages not handled by Greenkeeper
  package.json
  yarn.lock
Labels: ready-for-review

#138 Remove manual Greenkeeper lockfile update
  .circleci/config.yml
  package.json
  yarn.lock
Labels: maintenance, ready-for-review

#139 Rename repo contribution guide
  .github/CONTRIBUTING.md
  README.md
  modules/node_modules/@colony/purser-core/README.md
  modules/node_modules/@colony/purser-ledger/README.md
  modules/node_modules/@colony/purser-metamask/README.md
  modules/node_modules/@colony/purser-software/README.md
  modules/node_modules/@colony/purser-trezor/README.md
Labels: maintenance

#140 Add correct modules named exports
  modules/node_modules/@colony/purser-core/index.js
  modules/node_modules/@colony/purser-ledger/index.js
  modules/node_modules/@colony/purser-metamask/index.js
  modules/node_modules/@colony/purser-software/index.js
  modules/node_modules/@colony/purser-trezor/index.js
Labels: bug

#141 Release 1.0.2
  modules/node_modules/@colony/purser-core/package.json
  modules/node_modules/@colony/purser-ledger/package.json
  modules/node_modules/@colony/purser-metamask/package.json
  modules/node_modules/@colony/purser-software/package.json
  modules/node_modules/@colony/purser-trezor/package.json
  package.json
Labels: maintenance

#148 Common Wallet Interface Docs Spelling Fix
  docs/_Interface_Common_Wallet_Interface.md
Labels: bug
