Repository JoinColony/purser, pull requests merged in 2018-10, with the labels that each got.

#152 Fix Husky's pre-commit hook
  .flowconfig
  .huskyrc
  .lintstagedrc
  package.json
Labels: maintenance, ready-for-review

#151 Refactor transaction signing restrictions
  docs/_Interface_Common_Wallet_Interface.md
  modules/node_modules/@colony/purser-core/defaults.js
  modules/node_modules/@colony/purser-core/flowtypes.js
  modules/node_modules/@colony/purser-core/helpers.js
  modules/node_modules/@colony/purser-core/messages.js
  modules/node_modules/@colony/purser-ledger/class.js
  modules/node_modules/@colony/purser-ledger/staticMethods.js
  modules/node_modules/@colony/purser-metamask/class.js
  modules/node_modules/@colony/purser-metamask/defaults.js
  modules/node_modules/@colony/purser-metamask/staticMethods.js
  modules/node_modules/@colony/purser-software/class.js
  modules/node_modules/@colony/purser-software/staticMethods.js
  modules/node_modules/@colony/purser-trezor/class.js
  modules/node_modules/@colony/purser-trezor/defaults.js
  modules/node_modules/@colony/purser-trezor/index.js
  modules/node_modules/@colony/purser-trezor/messages.js
  modules/node_modules/@colony/purser-trezor/staticMethods.js
  modules/tests/purser-core/helpers/transactionObjectValidator.test.js
  modules/tests/purser-ledger/class.test.js
  modules/tests/purser-ledger/staticMethods/signTransaction.test.js
  modules/tests/purser-metamask/class.test.js
  modules/tests/purser-software/class.test.js
  modules/tests/purser-software/staticMethods/signTransaction.test.js
  modules/tests/purser-trezor/class.test.js
  modules/tests/purser-trezor/staticMethods/signTransaction.test.js
Labels: bug

#153 Release 1.1.0
  modules/node_modules/@colony/purser-core/package.json
  modules/node_modules/@colony/purser-ledger/package.json
  modules/node_modules/@colony/purser-metamask/package.json
  modules/node_modules/@colony/purser-software/package.json
  modules/node_modules/@colony/purser-trezor/package.json
  package.json
Labels: maintenance

#154 Fix ethers imports that changed in v4
  jest.config.js
  modules/node_modules/@colony/purser-core/flowtypes.js
  modules/node_modules/@colony/purser-core/genericWallet.js
  modules/node_modules/@colony/purser-software/class.js
  modules/node_modules/@colony/purser-software/index.js
  modules/node_modules/@colony/purser-software/staticMethods.js
  modules/tests/mocks/ethers/utils/hdnode.js
  modules/tests/mocks/ethers/utils/index.js
  modules/tests/mocks/ethers/utils/json-wallet.js
  modules/tests/mocks/ethers/utils/secret-storage.js
  modules/tests/mocks/ethers/wallet/index.js
  modules/tests/purser-core/genericWallet.test.js
  modules/tests/purser-software/class.test.js
  modules/tests/purser-software/open.test.js
  modules/tests/purser-software/staticMethods/verifyMessage.test.js
  yarn.lock
Labels: bug

#155 Release 1.1.1
  modules/node_modules/@colony/purser-core/package.json
  modules/node_modules/@colony/purser-software/package.json
  package.json
Labels: maintenance

#156 Fix `purser-software` mnemonic when creating a new instance
  modules/node_modules/@colony/purser-ledger/README.md
  modules/node_modules/@colony/purser-metamask/README.md
  modules/node_modules/@colony/purser-software/README.md
  modules/node_modules/@colony/purser-software/index.js
  modules/node_modules/@colony/purser-trezor/README.md
Labels: bug

#157 Release 1.1.2
  modules/node_modules/@colony/purser-ledger/package.json
  modules/node_modules/@colony/purser-metamask/package.json
  modules/node_modules/@colony/purser-software/package.json
  modules/node_modules/@colony/purser-trezor/package.json
  package.json
Labels: maintenance

#163 Add readme badges and update banner
  README.md
Labels: maintenance

#164 Update `purser-metamask` to be EIP-1102 compliant
  .flowconfig
  docs/_Modules_purser-metamask.md
  jest.config.js
  modules/node_modules/@colony/purser-core/genericWallet.js
  modules/node_modules/@colony/purser-metamask/flowtypes.js
  modules/node_modules/@colony/purser-metamask/helpers.js
  modules/node_modules/@colony/purser-metamask/index.js
  modules/node_modules/@colony/purser-metamask/messages.js
  modules/node_modules/@colony/purser-metamask/methodLinks.js
  modules/tests/mocks/@colony/purser-metamask/helpers.js
  modules/tests/mocks/web3.js
  modules/tests/purser-metamask/class.test.js
  modules/tests/purser-metamask/helpers/detect.test.js
  modules/tests/purser-metamask/helpers/getInpageProvider.test.js
  modules/tests/purser-metamask/helpers/methodCaller.test.js
  modules/tests/purser-metamask/open.test.js
  modules/tests/purser-metamask/staticMethods/signMessage.test.js
  modules/tests/purser-metamask/staticMethods/verifyMessage.test.js
  package.json
  yarn.lock
Labels: maintenance

#165 Release 1.2.0 Release Candidate 0
  docs/_Modules_purser-metamask.md
  modules/node_modules/@colony/purser-core/package.json
  modules/node_modules/@colony/purser-metamask/package.json
  modules/node_modules/@colony/purser-software/package.json
  package.json
Labels: maintenance

#166 Fix `purser-metamask` to check if Metamask is on a pre-release version
  modules/node_modules/@colony/purser-metamask/helpers.js
Labels: bug

#167 Release 1.2.0 Release Candidate 1
  modules/node_modules/@colony/purser-metamask/package.json
  package.json
Labels: maintenance

#170 Fix purser-metamask .sign() to return signed transaction hex
  modules/node_modules/@colony/purser-metamask/flowtypes.js
  modules/node_modules/@colony/purser-metamask/methodLinks.js
  modules/node_modules/@colony/purser-metamask/staticMethods.js
  modules/tests/purser-metamask/staticMethods/signTransaction.test.js
Labels: bug
