Repository JoinColony/purser, pull requests merged in 2019-07, with the labels that each got.

#247 Upgrade `eslint-plugin-flowtype` to version `3.11.1`
  package.json
  yarn.lock
Labels: maintenance

#246 purser-metamask will throw when cancelling signing a message or transaction
  modules/node_modules/@colony/purser-metamask/staticMethods.js
  modules/tests/purser-metamask/staticMethods/signMessage.test.js
  modules/tests/purser-metamask/staticMethods/signTransaction.test.js
Labels: feature

#250 Release v2.3.0 Minor
  modules/node_modules/@colony/purser-core/package.json
  modules/node_modules/@colony/purser-ledger/package.json
  modules/node_modules/@colony/purser-metamask/package.json
  modules/node_modules/@colony/purser-software/package.json
  modules/node_modules/@colony/purser-trezor/package.json
  package.json
Labels: maintenance

#251 Adjust error handling for static methods (MetaMask/Trezor)
  modules/node_modules/@colony/purser-metamask/staticMethods.js
  modules/node_modules/@colony/purser-trezor/staticMethods.js
  modules/tests/purser-metamask/staticMethods/signMessage.test.js
  modules/tests/purser-metamask/staticMethods/signTransaction.test.js
  modules/tests/purser-metamask/staticMethods/verifyMessage.test.js
  modules/tests/purser-trezor/staticMethods/signMessage.test.js
  modules/tests/purser-trezor/staticMethods/signTransaction.test.js
Labels: feature

#254 Release v2.4.1 Patch
  modules/node_modules/@colony/purser-ledger/package.json
  modules/node_modules/@colony/purser-metamask/package.json
  modules/node_modules/@colony/purser-trezor/package.json
  package.json
Labels: maintenance

#261 Add (basic) custom chain support (e.g. Görli)
  modules/node_modules/@colony/purser-core/helpers.js
  modules/node_modules/@colony/purser-ledger/staticMethods.js
  modules/node_modules/@colony/purser-metamask/staticMethods.js
  modules/node_modules/@colony/purser-trezor/staticMethods.js
  modules/tests/mocks/@colony/purser-core/helpers.js
  modules/tests/purser-ledger/staticMethods/signTransaction.test.js
  modules/tests/purser-metamask/staticMethods/signTransaction.test.js
  modules/tests/purser-trezor/staticMethods/signTransaction.test.js
  package.json
Labels: bug

#262 Upgrade `@ledgerhq/hw-app-eth` dependency
  package.json
  yarn.lock
Labels: maintenance

#263 Upgrade `@ledgerhq/hw-transport-u2f` dependency
  package.json
  yarn.lock
Labels: maintenance

#264 Release v2.5.0 Minor
  modules/node_modules/@colony/purser-core/package.json
  modules/node_modules/@colony/purser-ledger/package.json
  modules/node_modules/@colony/purser-metamask/package.json
  modules/node_modules/@colony/purser-trezor/package.json
  package.json
Labels: maintenance

#265 Add MetaMask/Infura workaround for pending transactions
  modules/node_modules/@colony/purser-core/defaults.js
  modules/node_modules/@colony/purser-core/genericWallet.js
  modules/node_modules/@colony/purser-core/helpers.js
  modules/node_modules/@colony/purser-ledger/index.js
  modules/node_modules/@colony/purser-metamask/staticMethods.js
  modules/node_modules/@colony/purser-software/index.js
  modules/node_modules/@colony/purser-trezor/index.js
  modules/tests/purser-core/genericWallet.test.js
  modules/tests/purser-ledger/open.test.js
  modules/tests/purser-trezor/open.test.js
  package.json
  yarn.lock
Labels: bug

#266 Release v2.5.1 Patch
  modules/node_modules/@colony/purser-core/package.json
  modules/node_modules/@colony/purser-ledger/package.json
  modules/node_modules/@colony/purser-metamask/package.json
  modules/node_modules/@colony/purser-software/package.json
  modules/node_modules/@colony/purser-trezor/package.json
  package.json
Labels: maintenance
